version: '3.1'

services:

  db-postgres:
    container_name: db-postgres
    image: postgres:9.6
    ports:
    - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: system

  graphql-docs:
    container_name: graphql-docs
    restart: always # to force restart until postgres is down
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 8383:8383
    environment:
      DB_PG_HOST_PORT: db-postgres:5432
